---
- name: Configure Azure VM
  hosts: GOxx0012
  become: yes
  tasks:
  - name: Update apt-get repo and cache
    apt: 
      update_cache: yes 
      force_apt_get: yes 
      cache_valid_time: 3600
  - name: Upgrade all apt packages
    apt: 
      upgrade: dist 
      force_apt_get: yes
  - name: ensure nginx is at the latest version
    apt:
      name: nginx
      state: latest
  - name: start nginx
    service: 
      name: nginx
      state: started
      enabled: yes